Vagrant.configure("2") do |config|

  ENV['VAGRANT_NO_PARALLEL'] = 'yes'
  config.vm.define :"control.dietstack" do |server|
    server.vm.box = "generic/debian9"
    server.ssh.insert_key = false
    server.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    server.ssh.forward_agent = true
    server.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    server.vm.hostname = "control.dietstack"
    # external network
    server.vm.network :private_network, :ip => "192.168.99.2", auto_config: false
    # openstack networks
    server.vm.network :private_network, :ip => "192.168.23.2"
    server.vm.synced_folder '../', '/root/dietstack', type: 'rsync', rsync_exclude: ".git/"
    server.vm.provider :libvirt do |domain|
      domain.memory = 8192
      domain.cpus = 2
      domain.nested = true
    end
    server.vm.provision :shell, privileged: false do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/$USER/.ssh/authorized_keys
        sudo bash -c "mkdir /root/.ssh/; echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
        sudo cp /root/dietstack/vagrant/interfaces_br-ex /etc/network/interfaces.d/br-ex
        sudo bash -c "apt-get install -y bridge-utils && ifup br-ex"
        sudo bash -c "VERSIONS=2 COMPUTE_NODE=false EXTERNAL_IP='192.168.99.2/24' DS_INTERFACE=eth2 /root/dietstack/ds.sh"
      SHELL
    end
  end


  (1..2).each do |i|
    config.vm.define :"compute#{i}.dietstack" do |server|
      server.vm.box = "generic/debian9"
      server.ssh.insert_key = false
      server.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
      server.ssh.forward_agent = true
      server.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      server.vm.hostname = "compute#{i}.dietstack"
      # external network
      server.vm.network :private_network, :ip => "192.168.99.#{i+2}"
      # openstack networks
      server.vm.network :private_network, :ip => "192.168.23.#{i+2}"
      server.vm.synced_folder '../', '/root/dietstack', type: 'rsync', rsync_exclude: ".git/"
      server.vm.provider :libvirt do |domain|
        domain.memory = 2048
        domain.cpus = 2
        domain.nested = true
      end
      server.vm.provision :shell, privileged: false do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/$USER/.ssh/authorized_keys
          sudo bash -c "mkdir /root/.ssh/; echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
          sudo bash -c "VERSIONS=2 CONTROL_NODE=false DS_INTERFACE=eth2 CONTROL_NODE_DS_IP=192.168.23.2 /root/dietstack/ds.sh"
        SHELL
      end
    end
  end
end
  
